# Generated by Django 5.1 on 2025-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
    ]
