# Generated by Django 5.1 on 2025-01-07 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_quiz_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education_app.parent'),
            preserve_default=False,
        ),
    ]
