# Generated by Django 5.1.4 on 2025-01-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0005_remove_quiz_answers_quiz_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
